environment                         = "dev"
project_name                        = "aksgitops"
location                            = "westcentralus"
subscription_id                     = "1bd9c71c-e648-453c-beaf-e5a084a52d50"
tenant_id                           = "ffcbd59c-ff21-4edc-b020-3a682dca7757"
aks_default_node_pool_vm_size       = "Standard_B2pls_v2" # cheapest found in free tier - k8s/deployment.yaml's resource requests/limits are sized to fit it
aks_k8s_version                     = "1.35.7"
argocd_namespace                    = "argocd"
argocd_project_repo_url             = "git@github.com:miltongabriel/AKSTerraformGitOps.git"
argocd_project_path                 = "k8s"
argocd_project_name                 = "webapp"
argocd_project_ssh_private_key_path = "../../argocd-ssh-key"                   # only used by bootstrap/02-keyvault
operator_aad_object_ids             = ["0820b7c1-f351-4b2a-b21d-cd704bd3192d"] # only used by bootstrap/90-operator