apiVersion: apps/v1
kind: Deployment
metadata:
  name: study-api-deploy
  labels:
    app: study-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: study-api
  template:
    metadata:
      labels:
        app: study-api
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: study-api
        image: gbenettiregistry.azurecr.io/study-api:5624be5e101b45b3877f21f29d09cf1f9cb933b5
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: PORT
          value: "3000"
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
