apiVersion: v1
kind: ConfigMap
metadata:
  namespace: webapp
  name: nginx-html-config
  labels:
    app: nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Kubernetes Nginx Static Page</title>
        <style>
            body { font-family: sans-serif; text-align: center; margin-top: 50px; }
        </style>
    </head>
    <body>
        <h1>Hello from Kubernetes!</h1>
        <p>This HTML file is dynamically injected via a ConfigMap.</p>
    </body>
    </html>